# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'datab.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1285, 825)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 20, 31, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 60, 21, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(30, 100, 31, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(30, 140, 31, 16))
        self.label_5.setObjectName("label_5")
        self.e9 = QtWidgets.QLineEdit(self.centralwidget)
        self.e9.setGeometry(QtCore.QRect(110, 100, 72, 24))
        self.e9.setObjectName("e9")
        self.e7 = QtWidgets.QLineEdit(self.centralwidget)
        self.e7.setGeometry(QtCore.QRect(110, 20, 72, 24))
        self.e7.setObjectName("e7")
        self.e10 = QtWidgets.QLineEdit(self.centralwidget)
        self.e10.setGeometry(QtCore.QRect(110, 140, 72, 24))
        self.e10.setObjectName("e10")
        self.e8 = QtWidgets.QLineEdit(self.centralwidget)
        self.e8.setGeometry(QtCore.QRect(110, 60, 72, 24))
        self.e8.setObjectName("e8")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1285, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "e7"))
        self.label_3.setText(_translate("MainWindow", "e8"))
        self.label_4.setText(_translate("MainWindow", "e9"))
        self.label_5.setText(_translate("MainWindow", "e10"))
