# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tx.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.ee = QtWidgets.QLineEdit(self.centralwidget)
        self.ee.setGeometry(QtCore.QRect(110, 50, 113, 21))
        self.ee.setObjectName("ee")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 50, 71, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(250, 50, 71, 16))
        self.label_3.setObjectName("label_3")
        self.ee_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.ee_2.setGeometry(QtCore.QRect(310, 50, 113, 21))
        self.ee_2.setObjectName("ee_2")
        self.ee_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.ee_3.setGeometry(QtCore.QRect(140, 140, 113, 21))
        self.ee_3.setObjectName("ee_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(40, 140, 91, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(40, 180, 91, 16))
        self.label_5.setObjectName("label_5")
        self.ee_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.ee_4.setGeometry(QtCore.QRect(140, 180, 113, 21))
        self.ee_4.setObjectName("ee_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "ip地址"))
        self.label_3.setText(_translate("MainWindow", "端口"))
        self.label_4.setText(_translate("MainWindow", "接收字节长度"))
        self.label_5.setText(_translate("MainWindow", "发送字节长度"))
